### ISSUE TITLE
Error with Python 3.5

### ISSUE THREAD

**Issue by imeraj** [sefakilic/goodreads#19]
I get the below error when I try to use goodreads wrapper - 

Traceback (most recent call last):
  File "./getQuotes.py", line 3, in <module>
    from goodreads import client
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/goodreads/client.py", line 2, in <module>
    from session import GoodreadsSession

Does this wrapper work with python3.5? 

Thanks.

**Comment by rkhwaja** [comment]
It definitely doesn't work with python 3.5 but you can make some simple changes so that it at least runs. e.g. for the imports you can change
from session import GoodreadsSession
to 
from session import goodreads.GoodreadsSession

**Comment by sefakilic** [comment]
Fixed
