### ISSUE TITLE
Shelves is not working

### ISSUE THREAD

**Issue by ChillarAnand** [sefakilic/goodreads#26]
``` py
import os


from goodreads import client

gr_key = os.environ.get('GR_KEY')
gr_secret = os.environ.get('GR_SECRET')
gc = client.GoodreadsClient(gr_key, gr_secret)
user = gc.user(9669859)
print(user.shelves())

```

This throws

``` py
→ py good_reads.py
Traceback (most recent call last):
  File "good_reads.py", line 10, in <module>
    print(user.shelves())
  File "/home/chillaranand/.virtualenvs/p35/lib/python3.5/site-packages/goodreads/shelf.py", line 7, in __repr__
    return self.name
  File "/home/chillaranand/.virtualenvs/p35/lib/python3.5/site-packages/goodreads/shelf.py", line 11, in name
    return self._shelf_dict['@name']
KeyError: '@name'

```

**Comment by tatianass** [comment]
I solved it removing the @name and @count.

**Comment by ChillarAnand** [comment]
Thanks @tatianass

**Comment by tatianass** [comment]
You're welcome. :)
