### ISSUE TITLE
pip install

### ISSUE THREAD

**Issue by sefakilic** [sefakilic/goodreads#4]
pip install gives the following error message:
```
Downloading/unpacking goodreads from https://pypi.python.org/packages/source/G/Goodreads/goodreads-0.2.1.tar.gz#md5=f7c04e3e368479e53a275ca840a5eef2
  Downloading goodreads-0.2.1.tar.gz
  Running setup.py (path:/tmp/pip_build_root/goodreads/setup.py) egg_info for package goodreads
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/goodreads/setup.py", line 7, in <module>
        long_description = pypandoc.convert('README.md', 'rst'),
      File "/usr/local/lib/python2.7/dist-packages/pypandoc.py", line 94, in convert
        outputfile=outputfile, filters=filters)
      File "/usr/local/lib/python2.7/dist-packages/pypandoc.py", line 112, in _convert
        raise RuntimeError('Missing format!')
    RuntimeError: Missing format!
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/goodreads/setup.py", line 7, in <module>

    long_description = pypandoc.convert('README.md', 'rst'),

  File "/usr/local/lib/python2.7/dist-packages/pypandoc.py", line 94, in convert

    outputfile=outputfile, filters=filters)

  File "/usr/local/lib/python2.7/dist-packages/pypandoc.py", line 112, in _convert

    raise RuntimeError('Missing format!')

RuntimeError: Missing format!

----------------------------------------
```

**Comment by sefakilic** [comment]
pandoc-ed README.md to .rst and removed pypandoc completely.
